version: "3.9"

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:22.7.2.15
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ch_data:/var/lib/clickhouse/
    ports:
      - 9000:9000
      - 8123:8123
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  ch_data:
    driver: local
